### ISSUE TITLE
google-private provider

### ISSUE THREAD

**Issue by romanini-ciandt** [GoogleCloudPlatform/terraform-google-autokey#4]
This is not an issue, just a question for maintainers:

Any particular reason this repo is using `google-private` provider instead of `google-beta` since `google_kms_autokey_config` is already available in beta?

I ask because I'd like to use AutoKey in an automation I'm working for [kms-solutions repo](https://github.com/googlecloudplatform/kms-solutions), and terraform-google-autokey module would be super helpful for me, but since google-private provider is not public, I would need to fork this repo, and I'd like to avoid that approach, if it is possible.

Thanks!

**Comment by mgaur10** [comment]
updated to support google-beta public release
